name: Build and deploy Node.js app to Azure Web App - react-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present  # 确保生成 dist 目录

      - name: Zip the dist folder
        run: zip -r release.zip ./dist/*  # 仅打包 dist 目录内容

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d dist  # 解压到 dist 目录

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}        # 改用简化的 Secret 名称
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}        # 改用简化的 Secret 名称
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # 改用简化的 Secret 名称

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'react-demo'
          slot-name: 'Production'
          package: dist  # 关键修改：指向解压后的 dist 目录
